### ISSUE TITLE
Non-existing DNS records won't get removed

### ISSUE THREAD

**Issue by erJasp** [failmap/failmap#8]
It seems that DNS records which have been discovered during a previous scan, have been removed from the zone and have been rescanned won't get removed from the database. 

For example: preproductie.defryskemarren.nl

<sup>Also: responding to e-mails would be nice :speak_no_evil:</sup>

**Comment by aequitas** [comment]
Hi Jasper, 

currently we are not using Github for development (just for exposure) so it would be preferred to create a ticket on our Gitlab environment (https://gitlab.com/failmap/admin) or using the servicedesk (info@faalkaart.nl).

I'll have a look into how we should communicate this on our Github page better in the future.

Regarding the email, I'll bring the relevant support ticket under attention with support.
